### PR TITLE
Update the scripts and documentation.

### PR DESCRIPTION
**Pull request by pingers**

### CODE REVIEW

**Comment by singularo** [comment]
Looks ok, Did a couple of additions, pretty sure its still broken atm though with 8.2 as the autoload stuff is different. Lets get this in, then convert it to use full composer install workflow - https://github.com/drupal-composer/drupal-project ?

**Comment by pingers** [comment]
Yeah... I reckon it's the way to go. Are we ready to do that for SM ❓

**Review by singularo — APPROVED** [review]
Lets git-r-done

**Comment by pingers** [comment]
Nope. Dead PR.

**Pull request closed without merging**
